#global:
#  slack_api_url: ""
#
#route:
#  receiver: 'spot-on-slack'
#  repeat_interval: 30m # 처음 알림 보내고 30분뒤 다시 알림 발송
#
#receivers:
#  - name: 'spot-on-slack'
#    slack_configs:
#      - channel: '#spot-on'
#        send_resolved: true
#        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
#        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"