spring:
  datasource:
    url: jdbc:mysql://mysql:3306/spoton-backend?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      connection-timeout: 30000
