#groups:
#  - name: alert_rules
#    rules:
#      - alert: HostOutOfMemory
#        # 사용 가능한 메모리 비율이 10% 미만인지를 확인
#        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
#        # Pending 상태 10초 이상 지속 시 슬랙 메세지 전송
#        for: 10s
#        labels:
#          severity: warning
#        annotations:
#          summary: Host out of memory (사용 가능 메모리 10% 미만)
#          description: '사용 가능한 메모리가 10% 미만이에요'