name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check commit message and PR title for "citest" trigger
      id: check_trigger
      run: |
        # 커밋 메시지 확인
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Commit message: $COMMIT_MESSAGE"

        # PR 제목 확인
        PR_TITLE=""
        if [[ -f "$GITHUB_EVENT_PATH" ]]; then
          PR_TITLE=$(jq --raw-output .pull_request.title $GITHUB_EVENT_PATH)
          echo "PR Title: $PR_TITLE"
        fi

        # 커밋 메시지나 PR 제목이 "citest"로 시작하는지 확인
        if [[ "$COMMIT_MESSAGE" == citest* || "$PR_TITLE" == citest* ]]; then
          echo "CI triggered because commit message or PR title starts with 'citest'"
        else
          echo "Skipping CI because commit message and PR title do not start with 'citest'"
          exit 0  # CI를 건너뛰기 위해 0으로 종료
        fi

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/wrapper-validation-action@v2
      with:
        gradle-version: '8.0'  # 원하는 Gradle 버전으로 설정

    - name: Build with Gradle
      run: ./gradlew build  # Gradle을 사용하여 빌드 실행

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
